import {readFile,writeFile} from 'node:fs/promises'
const base=await readFile(new URL('025_fundacao_preflight_readonly.sql',import.meta.url),'utf8')
let sql=base.replace("NOT engmarq_private.cnpj_valido(cnpj)",()=>`NOT (btrim(cnpj) COLLATE "C" ~ '^([0-9A-Za-z]{12}[0-9]{2}|[0-9A-Za-z]{2}\\.[0-9A-Za-z]{3}\\.[0-9A-Za-z]{3}/[0-9A-Za-z]{4}-[0-9]{2})$' AND cnpj_canonico IS NOT NULL AND cnpj_canonico<>repeat(substr(cnpj_canonico,1,1),14) AND substr(cnpj_canonico,13,1)=(SELECT CASE WHEN sum((ascii(substr(cnpj_canonico,j::int,1))-48)*w)%11<2 THEN 0 ELSE 11-sum((ascii(substr(cnpj_canonico,j::int,1))-48)*w)%11 END::text FROM unnest(ARRAY[5,4,3,2,9,8,7,6,5,4,3,2]) WITH ORDINALITY weights(w,j)) AND substr(cnpj_canonico,14,1)=(SELECT CASE WHEN sum((ascii(substr(cnpj_canonico,j::int,1))-48)*w)%11<2 THEN 0 ELSE 11-sum((ascii(substr(cnpj_canonico,j::int,1))-48)*w)%11 END::text FROM unnest(ARRAY[6,5,4,3,2,9,8,7,6,5,4,3,2]) WITH ORDINALITY weights(w,j)))`)
.replace('APROVADO PARA REVISÃO — NÃO AUTORIZA EXPOSIÇÃO PÚBLICA','APROVADO PARA REVISÃO — NÃO AUTORIZA APLICAÇÃO').replace('REPROVADO — 025 NÃO VALIDADA','REPROVADO — NÃO APLICAR 025')
const additions=[]
// PL/pgSQL event_trigger functions reject ordinary SQL invocation before their
// body executes. EXECUTE is not evidence of an exposed definer RPC for this
// exact type/language. Keep a warning AND the independent strict body contract.
const ddlOnly="p.prorettype='event_trigger'::regtype AND EXISTS(SELECT 1 FROM pg_language language WHERE language.oid=p.prolang AND language.lanname='plpgsql')"
const add=(category,name,result,status,details="'{}'::jsonb",from='')=>additions.push(`UNION ALL SELECT '${category}',${name},${result},${status},${details} ${from}`)
add('BASELINE',"'Colaboradores ativos/inativos/total'","count(*)::text","'OK'","jsonb_build_object('ativos',count(*) FILTER(WHERE active),'inativos',count(*) FILTER(WHERE NOT active),'estado_nulo',count(*) FILTER(WHERE active IS NULL),'fingerprint_estado',md5(coalesce(jsonb_agg(jsonb_build_object('id',id,'empresa_id',empresa_id,'active',active) ORDER BY id)::text,'[]')))",'FROM public.colaboradores')
add('ESTADO',"'Resumo empresas e backfill'","count(*)::text","'OK'",`jsonb_build_object('total_empresas',count(*),'empresas_existentes',coalesce(jsonb_agg(id ORDER BY id),'[]'),'com_comercial',count(*) FILTER(WHERE comercial),'com_features',count(*) FILTER(WHERE features),'com_limites',count(*) FILTER(WHERE limites),'com_uso',count(*) FILTER(WHERE uso),'elegiveis',count(*) FILTER(WHERE NOT comercial AND NOT features),'nao_elegiveis',count(*) FILTER(WHERE comercial OR features),'parcialmente_configuradas',count(*) FILTER(WHERE (comercial OR features OR limites OR uso) AND NOT(comercial AND features AND limites AND uso)))`, `FROM (SELECT e.id,EXISTS(SELECT 1 FROM empresa_comercial x WHERE x.empresa_id=e.id) comercial,EXISTS(SELECT 1 FROM empresa_features x WHERE x.empresa_id=e.id) features,EXISTS(SELECT 1 FROM empresa_limites x WHERE x.empresa_id=e.id) limites,EXISTS(SELECT 1 FROM empresa_uso x WHERE x.empresa_id=e.id) uso FROM empresas e) states`)
add('ESTADO',"'Previsão exata: '||e.id","CASE WHEN x.empresa_id IS NULL AND NOT EXISTS(SELECT 1 FROM empresa_features f WHERE f.empresa_id=e.id) THEN 'ELEGÍVEL' ELSE 'NÃO ELEGÍVEL' END","'ATENÇÃO'",`jsonb_build_object('empresa_id',e.id,'possui_comercial',x.empresa_id IS NOT NULL,'possui_features',EXISTS(SELECT 1 FROM empresa_features f WHERE f.empresa_id=e.id),'possui_limite',l.empresa_id IS NOT NULL,'possui_uso',u.empresa_id IS NOT NULL,'ativos',(SELECT count(*) FROM colaboradores c WHERE c.empresa_id=e.id AND c.active),'inativos',(SELECT count(*) FROM colaboradores c WHERE c.empresa_id=e.id AND NOT c.active),'total',(SELECT count(*) FROM colaboradores c WHERE c.empresa_id=e.id),'limite_atual',l.max_colaboradores_ativos,'inserir_comercial_legado',x.empresa_id IS NULL,'inserir_limite_ilimitado',l.empresa_id IS NULL,'inserir_uso_real',u.empresa_id IS NULL,'concessoes',CASE WHEN x.empresa_id IS NULL AND NOT EXISTS(SELECT 1 FROM empresa_features f WHERE f.empresa_id=e.id) THEN to_jsonb(ARRAY['empresa.cadastro','usuarios.gestao','colaboradores.gestao','treinamentos','exames','documentos','relatorios.sst']) ELSE '[]'::jsonb END,'epi',false)`, 'FROM empresas e LEFT JOIN empresa_comercial x ON x.empresa_id=e.id LEFT JOIN empresa_limites l ON l.empresa_id=e.id LEFT JOIN empresa_uso u ON u.empresa_id=e.id')
for(const [t,col,parent] of [['documentos','empresa_id','empresas'],['treinamentos','empresa_id','empresas'],['user_profiles','empresa_id','empresas'],['colaboradores','empresa_id','empresas'],['documentos','colaborador_id','colaboradores'],['treinamentos','colaborador_id','colaboradores'],['matriz_treinamentos','funcao_id','funcoes']]){
const predicate=col==='empresa_id'? 'p.id IS NULL':'p.id IS NULL OR p.empresa_id IS DISTINCT FROM r.empresa_id'
add('INTEGRIDADE',`'Tenant ${t}.${col}'`,'count(*)::text',"CASE WHEN count(*)=0 THEN 'OK' ELSE 'BLOQUEIO' END","'{}'::jsonb",`FROM public.${t} r LEFT JOIN public.${parent} p ON p.id=r.${col} WHERE r.${col} IS NOT NULL AND (${predicate})`)
}
// Optional columns: inspect JSON instead of binding absent columns.
add('INTEGRIDADE',"'Treinamentos x função opcional'",'count(*)::text',"CASE WHEN count(*)=0 THEN 'OK' ELSE 'BLOQUEIO' END","'{}'::jsonb","FROM treinamentos r LEFT JOIN funcoes f ON f.id::text=to_jsonb(r)->>'funcao_id' WHERE to_jsonb(r)->>'funcao_id' IS NOT NULL AND f.empresa_id IS DISTINCT FROM r.empresa_id")
add('STORAGE',"'Inventário bucket: '||b.id","CASE WHEN b.id IN ('documentos','logos','assinaturas') THEN 'ESPERADO' ELSE 'INESPERADO' END",`CASE WHEN b.public OR (b.id NOT IN ('documentos','logos','assinaturas') AND (EXISTS(SELECT 1 FROM storage.objects o WHERE o.bucket_id=b.id) OR EXISTS(SELECT 1 FROM pg_policies WHERE schemaname='storage' AND tablename='objects' AND ((coalesce(qual,'')||coalesce(with_check,'')) NOT LIKE '%bucket_id%' OR position(b.id in coalesce(qual,'')||coalesce(with_check,''))>0)))) THEN 'BLOQUEIO' WHEN b.id NOT IN ('documentos','logos','assinaturas') THEN 'ATENÇÃO' ELSE 'OK' END`,"jsonb_build_object('publico',b.public,'privado',NOT b.public,'potencial_legado',b.id ~* '(epi|assinatur)','file_size_limit',b.file_size_limit,'mime',b.allowed_mime_types,'objetos',(SELECT count(*) FROM storage.objects o WHERE o.bucket_id=b.id),'namespace_esperado','empresa_id/...')",'FROM storage.buckets b')
add('STORAGE',"'Objetos fora do namespace: '||o.bucket_id",'count(*)::text',"CASE WHEN count(*)=0 THEN 'OK' ELSE 'BLOQUEIO' END","'{}'::jsonb","FROM storage.objects o LEFT JOIN empresas e ON e.id::text=split_part(o.name,'/',1) WHERE e.id IS NULL OR split_part(o.name,'/',2)='' GROUP BY o.bucket_id")
add('STORAGE',"'Policies: '||policyname",'cmd',"'ATENÇÃO'","to_jsonb(p)","FROM pg_policies p WHERE schemaname='storage' AND tablename IN ('objects','buckets')")
add('SEGURANCA',"'EXECUTE: '||p.oid::regprocedure::text", "CASE WHEN p.prosecdef THEN 'SECURITY DEFINER' ELSE 'INVOKER' END",`CASE WHEN ${ddlOnly} THEN 'ATENÇÃO' WHEN p.prosecdef AND (EXISTS(SELECT 1 FROM aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) a WHERE a.privilege_type='EXECUTE' AND a.grantee=0) OR EXISTS(SELECT 1 FROM pg_roles r WHERE r.rolname NOT IN ('postgres','anon','authenticated','service_role') AND NOT r.rolsuper AND has_function_privilege(r.oid,p.oid,'EXECUTE'))) THEN 'BLOQUEIO' ELSE 'OK' END`, `jsonb_build_object('definition',pg_get_functiondef(p.oid),'public',EXISTS(SELECT 1 FROM aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) a WHERE a.privilege_type='EXECUTE' AND a.grantee=0),'grantees',(SELECT jsonb_agg(jsonb_build_object('role',r.rolname,'execute',has_function_privilege(r.oid,p.oid,'EXECUTE')) ORDER BY r.rolname) FROM pg_roles r),'service_role','técnico; não implica Super Admin funcional','surface',CASE WHEN ${ddlOnly} THEN 'DDL_ONLY: PL/pgSQL event_trigger nao pode ser chamada via SQL comum; revisar corpo e vinculo em CONTRATO_025' ELSE 'FUNCTION: revisar EXECUTE e contrato' END)`, "FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname IN ('public','engmarq_private') AND p.prokind='f' AND NOT EXISTS(SELECT 1 FROM pg_depend d WHERE d.classid='pg_proc'::regclass AND d.objid=p.oid AND d.deptype='e')")
add('INTEGRIDADE',"'FK existente: '||k.conrelid::regclass::text||'.'||k.conname",'pg_get_constraintdef(k.oid)',"CASE WHEN k.convalidated THEN 'OK' ELSE 'BLOQUEIO' END","jsonb_build_object('composta',cardinality(k.conkey)>1,'validated',k.convalidated)","FROM pg_constraint k JOIN pg_namespace n ON n.oid=k.connamespace WHERE k.contype='f' AND n.nspname IN ('public','engmarq_private')")
add('OPCIONAIS',"'EPI/Assinaturas: '||check_name",`CASE WHEN result='ausente' THEN 'AUSENTE' WHEN status='OK' THEN 'PRESENTE-SEGURO' WHEN status='BLOQUEIO' THEN 'BLOQUEADOR' ELSE 'PRESENTE-REQUER-HARDENING' END`,'status','details',"FROM contract WHERE check_name ~* '(fichas_epi|assinatur|(^|[._:])epi([._:(]|$))'")
add('OPCIONAIS',"'EPI/Assinaturas ausentes'","'AUSENTE'","'OK'","'{}'::jsonb","WHERE NOT EXISTS(SELECT 1 FROM contract WHERE check_name ~* '(fichas_epi|assinatur|(^|[._:])epi([._:(]|$))' AND result<>'ausente')")
// Frozen column manifest enables comparisons after new columns; existing legacy fingerprints stay compatible.
add('BASELINE',"'Manifesto operacional: '||n.nspname||'.'||c.relname",'count(*)::text',"'OK'","jsonb_build_object('colunas',jsonb_agg(a.attname ORDER BY a.attnum),'comparacao','projetar somente estas colunas; comparar fingerprints Preservação; tabelas comerciais comparar decisões anteriores e apenas inserções previstas')","FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace JOIN pg_attribute a ON a.attrelid=c.oid AND a.attnum>0 AND NOT a.attisdropped WHERE n.nspname IN ('public','engmarq_private','storage') AND c.relkind='r' GROUP BY n.nspname,c.relname")
for(const t of ['empresa_comercial','empresa_features','empresa_limites','empresa_uso','features'])add('BASELINE_COMERCIAL',`'Decisões anteriores: ${t}'`,"md5(coalesce(jsonb_agg(to_jsonb(r) ORDER BY to_jsonb(r)::text)::text,'[]'))","'OK'","jsonb_build_object('total',count(*),'estrategia','preservar linhas anteriores; novas linhas somente conforme previsão por empresa')",`FROM public.${t} r`)

add('INTEGRIDADE',"'FK dados/tenant: '||k.conrelid::regclass::text||'.'||k.conname",
 "(xpath('/table/row/violacoes/text()',query_to_xml(format('SELECT count(*) AS violacoes FROM %I.%I r WHERE %s AND NOT EXISTS (SELECT 1 FROM %I.%I p WHERE %s)',sn.nspname,sc.relname,parts.nonnull,tn.nspname,tc.relname,parts.matches||CASE WHEN cols.src_tenant AND cols.dst_tenant THEN ' AND p.empresa_id IS NOT DISTINCT FROM r.empresa_id' ELSE '' END),true,false,'')))[1]::text",
 "CASE WHEN (xpath('/table/row/violacoes/text()',query_to_xml(format('SELECT count(*) AS violacoes FROM %I.%I r WHERE %s AND NOT EXISTS (SELECT 1 FROM %I.%I p WHERE %s)',sn.nspname,sc.relname,parts.nonnull,tn.nspname,tc.relname,parts.matches||CASE WHEN cols.src_tenant AND cols.dst_tenant THEN ' AND p.empresa_id IS NOT DISTINCT FROM r.empresa_id' ELSE '' END),true,false,'')))[1]::text='0' THEN 'OK' ELSE 'BLOQUEIO' END",
 "jsonb_build_object('definition',pg_get_constraintdef(k.oid),'tenant_aware',cols.src_tenant AND cols.dst_tenant,'match_type',k.confmatchtype)",
 `FROM pg_constraint k JOIN pg_class sc ON sc.oid=k.conrelid JOIN pg_namespace sn ON sn.oid=sc.relnamespace JOIN pg_class tc ON tc.oid=k.confrelid JOIN pg_namespace tn ON tn.oid=tc.relnamespace
 CROSS JOIN LATERAL (SELECT '('||string_agg(format('r.%I IS NOT NULL',sa.attname),CASE WHEN k.confmatchtype='f' THEN ' OR ' ELSE ' AND ' END ORDER BY keys.ord)||')' nonnull,string_agg(format('p.%I = r.%I',ta.attname,sa.attname),' AND ' ORDER BY keys.ord) matches
 FROM unnest(k.conkey,k.confkey) WITH ORDINALITY keys(src,dst,ord) JOIN pg_attribute sa ON sa.attrelid=k.conrelid AND sa.attnum=keys.src JOIN pg_attribute ta ON ta.attrelid=k.confrelid AND ta.attnum=keys.dst) parts
 CROSS JOIN LATERAL (SELECT EXISTS(SELECT 1 FROM pg_attribute WHERE attrelid=k.conrelid AND attname='empresa_id' AND NOT attisdropped) src_tenant,EXISTS(SELECT 1 FROM pg_attribute WHERE attrelid=k.confrelid AND attname='empresa_id' AND NOT attisdropped) dst_tenant) cols
 WHERE k.contype='f' AND sn.nspname IN ('public','engmarq_private') AND sc.relkind='r' AND tc.relkind='r'`)
add('BASELINE_ADICIONAL',"'Fingerprint adicional: '||n.nspname||'.'||c.relname",
 "(xpath('/table/row/fingerprint/text()',query_to_xml(format('SELECT md5(coalesce(jsonb_agg(to_jsonb(r) ORDER BY to_jsonb(r)::text)::text,''[]'')) fingerprint FROM %I.%I r',n.nspname,c.relname),true,false,'')))[1]::text", "'OK'",
 "jsonb_build_object('comparacao','projetar colunas do manifesto operacional; distinguir inser??es comerciais previstas')",
 "FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname IN ('public','engmarq_private') AND c.relkind='r'")
add('CNPJ',"'Contrato CNPJ metadados: '||p.oid::regprocedure::text", "md5(replace(p.prosrc,E'\\r\\n',E'\\n'))",
 "CASE WHEN l.lanname=CASE WHEN p.proname='cnpj_valido' THEN 'plpgsql' ELSE 'sql' END AND p.provolatile='i' AND NOT p.prosecdef AND p.prorettype=CASE WHEN p.proname='cnpj_valido' THEN 'boolean'::regtype ELSE 'text'::regtype END AND p.proconfig=ARRAY['search_path=\"\"'] AND p.proisstrict=(p.proname='cnpj_canonico') THEN 'OK' ELSE 'BLOQUEIO' END",
 "jsonb_build_object('definition',pg_get_functiondef(p.oid),'execucao','n?o chamada; contrato de corpo/hash conferido em CONTRATO_025')",
 "FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace JOIN pg_language l ON l.oid=p.prolang WHERE n.nspname='engmarq_private' AND p.proname IN ('cnpj_valido','cnpj_canonico')")

add('BASELINE_COMERCIAL',"'Linha anterior: '||t.tabela||':'||t.identidade",'t.fingerprint',"'OK'","jsonb_build_object('empresa_id',t.empresa_id,'comparacao','preservar esta linha; novas linhas somente conforme previsão')",`FROM (
 SELECT 'empresa_comercial' tabela,empresa_id::text empresa_id,empresa_id::text identidade,md5(to_jsonb(r)::text) fingerprint FROM empresa_comercial r
 UNION ALL SELECT 'empresa_features',empresa_id::text,empresa_id::text||':'||feature_key,md5(to_jsonb(r)::text) FROM empresa_features r
 UNION ALL SELECT 'empresa_limites',empresa_id::text,empresa_id::text,md5(to_jsonb(r)::text) FROM empresa_limites r
 UNION ALL SELECT 'empresa_uso',empresa_id::text,empresa_id::text,md5(to_jsonb(r)::text) FROM empresa_uso r) t`)
add('INTEGRIDADE',"'Ambiguidades de estado comercial'",'count(*)::text',"CASE WHEN count(*)=0 THEN 'OK' ELSE 'BLOQUEIO' END","jsonb_build_object('regra','configurada sem limite explícito ou estado ativo desconhecido')",`FROM (SELECT e.id FROM empresas e WHERE (EXISTS(SELECT 1 FROM empresa_comercial c WHERE c.empresa_id=e.id) OR EXISTS(SELECT 1 FROM empresa_features f WHERE f.empresa_id=e.id)) AND NOT EXISTS(SELECT 1 FROM empresa_limites l WHERE l.empresa_id=e.id) UNION ALL SELECT empresa_id FROM colaboradores WHERE active IS NULL) ambiguidades`)
sql=sql.replace('),numbered AS', '\n'+additions.join('\n')+'\n),numbered AS')
// Enrich existing checks, preserving their status and count. Never execute an
// unknown remote function or approve platform-looking objects by name/hash.
sql=sql.replace('FROM raw),', `FROM (
 SELECT category,check_name,result,status,details ||
 coalesce((SELECT jsonb_build_object('origem_funcao',jsonb_build_object(
  'definition',pg_get_functiondef(p.oid),'language',l.lanname,'acl',p.proacl::text,
  'raw_prosrc_md5',md5(replace(p.prosrc,E'\\r\\n',E'\\n')),
  'extension',(SELECT jsonb_agg(e.extname ORDER BY e.extname) FROM pg_depend d JOIN pg_extension e ON e.oid=d.refobjid WHERE d.classid='pg_proc'::regclass AND d.objid=p.oid AND d.refclassid='pg_extension'::regclass AND d.deptype='e'),
  'event_triggers',(SELECT coalesce(jsonb_agg(jsonb_build_object('name',t.evtname,'event',t.evtevent,'enabled',t.evtenabled,'tags',t.evttags,'owner',pg_get_userbyid(t.evtowner)) ORDER BY t.evtname),'[]'::jsonb) FROM pg_event_trigger t WHERE t.evtfoid=p.oid),
  'dependencias',(SELECT coalesce(jsonb_agg(to_jsonb(d) ORDER BY d.classid,d.objid,d.objsubid),'[]'::jsonb) FROM pg_depend d WHERE d.refclassid='pg_proc'::regclass AND d.refobjid=p.oid)))
 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace JOIN pg_language l ON l.oid=p.prolang
 WHERE n.nspname IN ('public','engmarq_private') AND p.prokind='f'
 AND check_name IN ('function:'||p.oid::regprocedure::text,'EXECUTE: '||p.oid::regprocedure::text)), '{}'::jsonb) ||
 coalesce((SELECT jsonb_build_object('origem_sequence',jsonb_build_object(
  'owner',pg_get_userbyid(c.relowner),'acl',c.relacl::text,
  'acl_nativo',(SELECT jsonb_agg(jsonb_build_object('grantee',CASE WHEN a.grantee=0 THEN 'PUBLIC' ELSE pg_get_userbyid(a.grantee) END,'grantor',pg_get_userbyid(a.grantor),'privilege',a.privilege_type,'grantable',a.is_grantable) ORDER BY a.grantee,a.privilege_type) FROM aclexplode(coalesce(c.relacl,acldefault('s',c.relowner))) a),
  'default_privileges_atuais',(SELECT coalesce(jsonb_agg(jsonb_build_object('creator',pg_get_userbyid(d.defaclrole),'schema',CASE WHEN d.defaclnamespace=0 THEN '*' ELSE dn.nspname END,'acl',d.defaclacl::text) ORDER BY d.defaclrole,d.defaclnamespace),'[]'::jsonb) FROM pg_default_acl d LEFT JOIN pg_namespace dn ON dn.oid=d.defaclnamespace WHERE d.defaclobjtype='S' AND d.defaclnamespace IN (0,c.relnamespace)),
  'dependencias',(SELECT coalesce(jsonb_agg(to_jsonb(d) ORDER BY d.refclassid,d.refobjid,d.refobjsubid),'[]'::jsonb) FROM pg_depend d WHERE d.classid='pg_class'::regclass AND d.objid=c.oid),
  'limite_evidencia','ACL/default privileges atuais nao registram data ou autor historico da concessao'))
 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
 WHERE c.relkind='S' AND check_name IN ('grant:'||n.nspname||'.'||c.relname||'.anon','grant:'||n.nspname||'.'||c.relname||'.authenticated','grant:'||n.nspname||'.'||c.relname||'.service_role')), '{}'::jsonb) details
 FROM raw
 ) enriched),`)
sql=sql.replace("END,'{}'::jsonb FROM totals)", `END,jsonb_build_object('bloqueios',
 (SELECT coalesce(jsonb_agg(jsonb_build_object('CATEGORIA',category,'CHECK',check_name,'RESULTADO',result,'STATUS',status,'DETALHES',details) ORDER BY category,check_name),'[]'::jsonb) FROM numbered WHERE status='BLOQUEIO'),
 'instrucao','Exportar os bloqueios completos; nenhuma divergencia autoriza correcao remota') FROM totals)`)
await writeFile(new URL('025_preflight_remoto_manual.sql',import.meta.url),sql)
console.log('Manual auditor generated offline')


